# Generated by Django 4.2 on 2023-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcao_funcionario_delete_pessoa_funcao_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='func',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
    ]
