# Generated by Django 4.2 on 2023-07-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_funcionario_funcionario_funcionario_func_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='logradouro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='func',
            field=models.CharField(max_length=100),
        ),
    ]
