# Generated by Django 4.2 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_log_funcionario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='area_interesse',
            field=models.CharField(choices=[('1', 'Contabilidade'), ('2', 'Plantio'), ('3', 'Colheita'), ('4', 'Distribuição'), ('5', 'Insumos')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
