# Generated by Django 4.2 on 2023-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_funcionario_area_interesse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='area_interesse',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
